//Any unpermissioned use of this plugin may be subjected to CopyRights

//If the user isn't OP when trying to create/break a sign, This Message will appear:
No-Permission-Message: "[1v1] You don't have permission!"

//When The User is teleportig to the 1v1 Match, This POPUP will appear:
Telporting-Message: Joining a 1v1 Match!

//Teleporting Color:
//Available Colors:
//GREEN = §2
//RED = §4
//PURPLE = §5
//YELLOW/ORANGE = §6
//AQUA = §3
//BLUE = §9
Teleporting-Message-Color: §9

//When a 1v1 Sign Is Created, This Message Will Appear:
Sign-Create-Message: "[1v1] Sign Created!"

//When a 1v1 SIgn Is Destroyed, This Message WIll Appear:
Sign-Destroy-Message: "[1v1] Sign Destroyed!"

//When World Is Full, This Message Will Appear:
World-Full-Message: "[1v1] This Match Is Full!"

//Tells the player to get in a corner:
Get-In-Corner-Message: "[1v1] Get In a corner!"
